---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Enable 10251/tcp port
  shell: "firewall-cmd --permanent --add-port=10251/tcp"

- name: Enable 10255/tcp port
  shell: "firewall-cmd --permanent --add-port=10255/tcp"

- name: Reload Firewall
  shell: "firewall-cmd --reload"

- name: Stop Firewall
  shell: "systemctl stop firewalld"
  ignore_errors: yes

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
