---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Enable 6443/tcp port
  shell: "firewall-cmd --permanent --add-port=6443/tcp"

- name: Enable 2379-2380/tcp ports
  shell: "firewall-cmd --permanent --add-port=2379-2380/tcp"

- name: Enable 10250/tcp port
  shell: "firewall-cmd --permanent --add-port=10250/tcp"

- name: Enable 10251/tcp port
  shell: "firewall-cmd --permanent --add-port=10251/tcp"

- name: Enable 10252/tcp port
  shell: "firewall-cmd --permanent --add-port=10252/tcp"

- name: Enable 10255/tcp port
  shell: "firewall-cmd --permanent --add-port=10255/tcp"

- name: Enable 80/tcp port
  shell: "firewall-cmd --permanent --add-port=80/tcp"

- name: Reload Firewall
  shell: "firewall-cmd --reload"

- name: stop firewall
  shell: "systemctl stop firewalld"
  ignore_errors: yes

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --apiserver-advertise-address {{ master_ip }} \
                 --ignore-preflight-errors {{ cpuCheck }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true
