---
- name: "Clean prometheus_dir if exist"
  file:
    path: "{{ prometheus_dir }}"
    state: absent
  ignore_errors: yes
  tags: prometheus

- name: "Create tmp directory"
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    mode: 0755
  ignore_errors: yes
  tags: prometheus

- name: "Copy prometheus and grafana YAML files"
  template:
    src: "{{ item }}"
    dest: "{{ prometheus_dir }}/{{ item  | basename }}"
  with_fileglob:
    - ../templates/*.yaml
  tags: prometheus

- name: "Creating namespace monitoring"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/namespace.yaml"
  ignore_errors: yes
  tags: prometheus
  
- name: "Creating the Service Account and Cluster Role"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/prometheus-rbac.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "create the config for prometheus to collect data from Kubernetes"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/prometheus-config.yaml"
  ignore_errors: yes
  tags: prometheus
 
- name: "Prometheus Deployment"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/prometheus-deploy.yaml"
  ignore_errors: yes
  tags: prometheus
  
- name: "Prometheus Service"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/prometheus-svc.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "Grafana Deployment"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ prometheus_dir }}/grafana.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "Grafana Deployment expose to LoadBalancer"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} expose deployment grafana --type=LoadBalancer --namespace=monitoring"
  ignore_errors: yes
  tags: prometheus

- name: "create node-exporter daemon set to export node information"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f{{ prometheus_dir }}/node-exporter.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "create kube-state-metrics deployment to collect metrics about the cluster"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f{{ prometheus_dir }}/state-metrics-deploy.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "service account and cluster role with the permission of getting cluster info for state-metrics."
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f{{ prometheus_dir }}/state-metrics-rbac.yaml"
  ignore_errors: yes
  tags: prometheus

- name: "Prometheus Deployment expose to LoadBalancer"
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} expose deployment prometheus --type=LoadBalancer --namespace=monitoring"
  ignore_errors: yes
  tags: prometheus


- name: "Clean-up"
  file:
    path: "{{ es_dir }}"
    state: absent
  ignore_errors: yes
  tags: prometheus
